data nalysts -SQL and data scientists

- SQl
- one shot quesry
- programmers
power BI -charts if they need to visualize

Data science
- excel
- line by line
- python (numpy and pandas - no licence fee because it is opensource
-scale, it can 
- scikeit - used for data prediction)
- matplot (used to visualize)

In [71]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


## Numpy
- they are work with arrays and- they are perfomant -> it works after with array
- because they use the C language in numpy
- statistical orientated (mean, mode)


In [72]:
import numpy as np

## shortcuts
- ctrl + alt + enter -. run the cell
- shift + enter -> move to next cell

In [73]:
marks= np.array([90, 80, 50, 40])
marks * 2

marks2 = [90, 80, 50, 40]
m = [x * 2 for x in marks2]
print(m)

[180, 160, 100, 80]


# making large arrays
- this will create 1, 20 times

# what is a matrix?
- collection of numbers arranged in columns and rows
  1 2 3
  4 5 6   3rowsx 3colums matrix
  7 8 9
  - if you combine the tw matrix together, they will add the first number of the fisrt set and add it to the fist number of the matrix
    second one, and so on..

In [74]:
np.ones(14)  #identity matrix  [1-D matrix]
np.zeros(14)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [75]:
np.arange(10)
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

## Operation that can be done with
- Addition
- multiplecation
- division
- Boolean matrix

In [76]:
np.arange(10) *2
np.arange(10) + 2
np.arange(10) / 2
np.arange(10) -2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [77]:
first_ten_nums = np.arange(1, 11)
all_greater_five = first_ten_nums > 5
print(first_ten_nums[all_greater_five])
print(first_ten_nums[first_ten_nums > 5])

[ 6  7  8  9 10]
[ 6  7  8  9 10]


## Task 1
Create a 1..200 numbers and provide a numpy array with all even numbers using skip

In [78]:
nums_200 = np.arange(2, 200, 2)
print(nums_200)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198]


## Task 2
- Create a 1..200 numbers and provide a numpy array with all even numbers without using  skip

In [79]:
nums_200 = np.arange(1, 200)
even_nums = nums_200 % 2 == 0
print(nums_200[even_nums])

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198]


# getting random numbers to the list

In [80]:
ages = np.random.randint(18, 60, 10)
ages_list = ages.tolist()
ages_list

[43, 51, 51, 58, 47, 49, 25, 39, 49, 32]

In [81]:
%%time  
double_ages = [age * 2 for age in ages_list]
print(double_ages)

[86, 102, 102, 116, 94, 98, 50, 78, 98, 64]
CPU times: total: 0 ns
Wall time: 1.01 ms


## statistical orientation - mode, mean, median, std

- mean -> average
- mode -> the most repeated
- median _ . the middle number
- standard diviation -> how far the gap between the average and every other value

In [82]:
marks = np.random.randint(40, 100, 10)
marks

array([55, 77, 45, 72, 76, 71, 62, 94, 43, 78])

## methods
- np.median(list)
- np.mean(list)
- np.mode(list)

In [83]:
print(marks)
print(marks.mean())
# print(marks.mode())

[55 77 45 72 76 71 62 94 43 78]
67.3


In [84]:
np.std(marks)

15.166080574756288

## Task 1
- in 10 years add 5% to the balance

## Task 2
at the end of ten years what will be the balance

In [85]:
investment = 1000
rate_of_invenstment = 1.05
years = np.arange(1, 11)
year_by_year = investment * (rate_of_invenstment) ** years
year_by_year



array([1050.        , 1102.5       , 1157.625     , 1215.50625   ,
       1276.2815625 , 1340.09564063, 1407.10042266, 1477.45544379,
       1551.32821598, 1628.89462678])

In [86]:
year_by_year[-1]  # the last element

1628.894626777442

In [87]:
diff = year_by_year[-1] - year_by_year[0]
average = (diff/year_by_year[0]) * 100
average


55.132821597851624

## useful methods

- string  methods
- unique
- min , max

In [88]:
salaries = np.random.randint(1_000, 10_000, 10)
print(salaries)


[9433 7628 6266 8754 5476 8234 3018 8716 1080 6522]


In [89]:
print(np.max(salaries), np.argmax(salaries))  # the index of the max
print(np.min(salaries), np.argmin(salaries))

9433 0
1080 8


In [90]:
nums = np.random.randint(1, 4, 10)
nums

array([2, 2, 2, 3, 1, 2, 2, 2, 2, 3])

## To get unique values
- np.unique(list)
- flipping the list

In [91]:
unique_nums = np.unique(nums)
np.flip(unique_nums)

array([3, 2, 1])

In [97]:
items = np.array([' Apple', 'banana ', 'GRAPE', 'cucumber', 'Pineapple', ' tomato ', 'Orange', ' lemon', 'Kiwi ', 'mango', 'blueberry ', ' raspberry'])
# np.char.lower(items) #the list is not manipulated at the top


array([' apple', 'banana ', 'grape', 'cucumber', 'pineapple', ' tomato ',
       'orange', ' lemon', 'kiwi ', 'mango', 'blueberry ', ' raspberry'],
      dtype='<U10')

## task 1
Normalize the array

In [106]:
stripped_items = np.char.strip(items)
lower_items = np.char.lower(stripped_items)
unique_items =np.unique(lower_items)
unique_items

array(['apple', 'banana', 'blueberry', 'cucumber', 'grape', 'kiwi',
       'lemon', 'mango', 'orange', 'pineapple', 'raspberry', 'tomato'],
      dtype='<U10')

## task 2
Filter Operations

a. Find and display all the items with letter b

In [122]:
starts_b=np.char.startswith('b')
starts_b
# b_items =[]
# for item in unique_items:
#     if item[0] == "b":
#      b_items.append(item)

# b_items

# b_item = []
# for item in items:
#     if item[0] == 'b':
#         b_item.append()
# b_item

#  b_items = [re.search(r'b+', unique_items)]
# b_items

['banana', 'blueberry']

In [125]:
has_e=[np.char.count(unique_items, 'e') == 1]_e
has_e

In [131]:
hourly_visitors = [468, 279,  73, 272 ,406 ,128 ,302 ,216, 140 , 82]
#Total visitors a day
np.sum(hourly_visitors)
#which is the peak hour
np.argmax(hourly_visitors)
#average
np.mean(hourly_visitors)

0

In [ ]:
num_3D = np.array([1,2,4], [6,7,77]),[9,20,24]