data analysts -SQL and data scientists

- SQl
- one shot query
- programmers
- power BI -charts if they need to visualize

Data science
- excel
- line by line
- python (numpy and pandas - no licence fee because it is opensource
-scale, it can 
- scikeit - used for data prediction)
- matplot (used to visualize)

In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


## Numpy
- they work with arrays and- they are perfomant -> it works after with array
- because they use the C language in numpy
- statistical orientated (mean, mode)


In [3]:
import numpy as np

## shortcuts
- ctrl + alt + enter -. run the cell
- shift + enter -> move to next cell

In [4]:
marks= np.array([90, 80, 50, 40])
marks * 2

marks2 = [90, 80, 50, 40]
m = [x * 2 for x in marks2]
print(m)

[180, 160, 100, 80]


# making large arrays
- this will create 1, 20 times

# what is a matrix?
- collection of numbers arranged in columns and rows
 - 1 2 3
 - 4 5 6   3rowsx 3colums matrix
 - 7 8 9
  - if you combine the two matrix together, they will add the first number of the fisrt set and add it to the fist number of the matrix
    second one, and so on..

In [5]:
np.ones(14)  #identity matrix  [1-D matrix]
np.zeros(14)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
n =np.arange(10)
np.arange(1, 10, 2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Operation that can be done with
- Addition
- multiplecation
- division
- Boolean matrix

In [29]:
normal = np.arange(10)
multiplying = np.arange(10) *2
adding = np.arange(10) + 2
divising = np.arange(10) / 2
subtracting = np.arange(10) -2

print(normal)
print(adding)
print(subtracting)
print(multiplying) 
print(divising)

[0 1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10 11]
[-2 -1  0  1  2  3  4  5  6  7]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [8]:
first_ten_nums = np.arange(1, 11)
all_greater_five = first_ten_nums > 5
print(first_ten_nums[all_greater_five])
print(first_ten_nums[first_ten_nums > 5])

[ 6  7  8  9 10]
[ 6  7  8  9 10]


## Task 1
Create a 1..200 numbers and provide a numpy array with all even numbers using skip

In [9]:
nums_200 = np.arange(2, 200, 2)
print(nums_200)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198]


## Task 2
- Create a 1..200 numbers and provide a numpy array with all even numbers without using  skip

In [10]:
nums_200 = np.arange(1, 200)
even_nums = nums_200 % 2 == 0
print(nums_200[even_nums])

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198]


# getting random numbers to the list

In [11]:
ages = np.random.randint(18, 60, 10)
ages_list = ages.tolist()
ages_list

[31, 57, 49, 51, 50, 33, 47, 25, 42, 20]

In [12]:
%%time  
double_ages = [age * 2 for age in ages_list]
print(double_ages)

[62, 114, 98, 102, 100, 66, 94, 50, 84, 40]
CPU times: total: 0 ns
Wall time: 0 ns


## statistical orientation - mode, mean, median, std, sum

- mean -> average
- mode -> the most repeated
- median _ . the middle number
- standard diviation -> how far the gap between the average and every other value
- sum(list)

In [13]:
marks = np.random.randint(40, 100, 10)
marks

array([71, 53, 62, 43, 74, 96, 82, 56, 47, 66])

## methods
- np.median(list)
- np.mean(list)
- np.mode(list)

In [14]:
print(marks)
print(marks.mean())
# print(marks.mode())

[71 53 62 43 74 96 82 56 47 66]
65.0


In [15]:
np.std(marks)

15.524174696260024

## Task 1
- in 10 years add 5% to the balance

## Task 2
at the end of ten years what will be the balance

In [16]:
investment = 1000
rate_of_invenstment = 1.05
years = np.arange(1, 11)
year_by_year = investment * (rate_of_invenstment) ** years
year_by_year



array([1050.        , 1102.5       , 1157.625     , 1215.50625   ,
       1276.2815625 , 1340.09564063, 1407.10042266, 1477.45544379,
       1551.32821598, 1628.89462678])

In [17]:
year_by_year[-1]  # the last element

1628.894626777442

In [18]:
diff = year_by_year[-1] - year_by_year[0]
average = (diff/year_by_year[0]) * 100
average


55.132821597851624

## useful methods

- string  methods
- unique
- min , max

In [19]:
salaries = np.random.randint(1_000, 10_000, 10)
print(salaries)


[8683 3958 7052 9321 3518 4225 1049 4538 7523 7738]


In [20]:
print(np.max(salaries), np.argmax(salaries))  # the index of the max
print(np.min(salaries), np.argmin(salaries))

9321 3
1049 6


In [21]:
nums = np.random.randint(1, 4, 10)
nums

array([3, 2, 3, 1, 3, 1, 1, 1, 1, 2])

## To get unique values
- np.unique(list)
- flipping the list

In [22]:
unique_nums = np.unique(nums)
np.flip(unique_nums)

array([3, 2, 1])

In [23]:
items = np.array([' Apple', 'banana ', 'GRAPE', 'cucumber', 'Pineapple', ' tomato ', 'Orange', ' lemon', 'Kiwi ', 'mango', 'blueberry ', ' raspberry'])
# np.char.lower(items) #the list is not manipulated at the top


## task 1
Normalize the array

In [30]:
stripped_items = np.char.strip(items) 
lower_items = np.char.lower(stripped_items)
unique_items =np.unique(lower_items)
unique_items

['Apple' 'banana' 'GRAPE' 'cucumber' 'Pineapple' 'tomato' 'Orange' 'lemon'
 'Kiwi' 'mango' 'blueberry' 'raspberry']


array(['apple', 'banana', 'blueberry', 'cucumber', 'grape', 'kiwi',
       'lemon', 'mango', 'orange', 'pineapple', 'raspberry', 'tomato'],
      dtype='<U10')

## task 2
Filter Operations

a. Find and display all the items with letter b

In [31]:
starts_b=np.char.startswith('b')
starts_b
# b_items =[]
# for item in unique_items:
#     if item[0] == "b":
#      b_items.append(item)

# b_items

# b_item = []
# for item in items:
#     if item[0] == 'b':
#         b_item.append()
# b_item

#  b_items = [re.search(r'b+', unique_items)]
# b_items

TypeError: startswith() missing 1 required positional argument: 'prefix'

In [32]:
has_e=[np.char.count(unique_items, 'e') == 1]
has_e

[array([ True, False, False,  True,  True, False,  True, False,  True,
        False,  True, False])]

In [ ]:
hourly_visitors = [468, 279,  73, 272 ,406 ,128 ,302 ,216, 140 , 82]
#Total visitors a day
np.sum(hourly_visitors)
#which is the peak hour
np.argmax(hourly_visitors)
#average
np.mean(hourly_visitors)

0

## 2D matrix
- array inside an array

In [ ]:
num_3D = np.array([[1,2,4], 
                  [6,7,77],
                  [9,20,24]])
num_3D.shape

array([[ 1,  2,  4],
       [ 6,  7, 77],
       [ 9, 20, 24]])

## shape
- returns the matrix structure. e.g (0,9)

In [ ]:
nums1 = np.arange(1, 10)
nums1.shape

(9,)

- reshaping a 1D array to a 2d array
- you can perfom statistical methods

In [ ]:
nums_3x3 = nums1.reshape(3,3)
np.sum(nums_3x3)

45

In [ ]:
print(num_3D)
np.sum(num_3D, axis=0) # the sum across the column
np.sum(num_3D, axis=1) #Te sum across the row

np.sum(np.sum(num_3D, axis=1))

[[ 1  2  4]
 [ 6  7 77]
 [ 9 20 24]]


150

In [ ]:
stats = np.random.randint(40, 100, 9)
stats

array([94, 59, 85, 72, 63, 44, 91, 94, 46])

In [ ]:
stats_3x3 = stats.reshape(3, 3)
stats_3x3  #Note to always have the right amount of values to fit
#the array

array([[94, 59, 85],
       [72, 63, 44],
       [91, 94, 46]])

In [ ]:
print(f'firt array\n" {num_3D}')
print(f'second {stats_3x3}')
print(f'results {num_3D + stats_3x3}')

firt array" [[ 1  2  4]
 [ 6  7 77]
 [ 9 20 24]]
second [[94 59 85]
 [72 63 44]
 [91 94 46]]
results [[ 95  61  89]
 [ 78  70 121]
 [100 114  70]]


## task 1

In [35]:
sensor1 = np.array([[23, 25, 22],
                    [20, 21, 20],
                    [26, 25, 24]])
 
sensor2 = np.array([[24, 23, 24],
                    [22, 22, 23],
                    [25, 26, 26]])
print(f'results \n {(sensor1 + sensor2)/2}')

results 
 [[23.5 24.  23. ]
 [21.  21.5 21.5]
 [25.5 25.5 25. ]]
[23.33333333 20.33333333 25.        ]


## Task 2
find the average cross the suit

In [ ]:
sensor1_across = np.mean(sensor1, axis=1)
print(sensor1_across)
sensor2_across = np.mean(sensor2, axis=1)
print(sensor2_across)

[23.33333333 20.33333333 25.        ]
[23.66666667 22.33333333 25.66666667]


## task 3
combine the average temp of sensor 1 and 2 per suite

In [ ]:
print((sensor1_across + sensor2_across) / 2)

[23.5        21.33333333 25.33333333]
